[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tabpfn-client"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.24.1",
    "pandas>=1.3.0",
    "omegaconf>=2.3.0",
    "tabpfn @ git+https://github.com/automl/TabPFN.git@main#egg=tabpfn",
]

[tool.hatch.metadata]
allow-direct-references = true
