name: linters

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: linters-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linters:
    name: Trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          version: "0.9.9"
          cache-python: true
      - name: Install deps
        run: uv sync --frozen --all-groups
      - name: Trunk check
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
        with:
          arguments: --all --no-progress --show-existing
