name: In pull request
on:
  pull_request:
    branches:
      - main

jobs:
  check_python_linting:
    name: Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./"
          version: 0.3.3

  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Run Test
        run: |
          python -m unittest discover -s tabpfn_client/tests -t tabpfn_client/tests
